baseURL = "http://blog.skycoin.net/blog/"
languageCode = "en-us"
title = "Skycoin Blog"

# config to deploy on github pages
publishDir = "docs"

#googleAnalytics = ""
#disqusShortname = ""

# hugo-xmin specific variables
theme = "hugo-xmin"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[author]
  name = "Skycoin"

[params]
  keywords = "skycoin"
  description = "Skycoin Project Updates"
  footer = "[skycoin.net](https://skycoin.net) | [Github](https://github.com/skycoin) | [Explorer](https://explorer.skycoin.net) | [Hugo XMin Theme](https://github.com/yihui/hugo-xmin)"
  email = ""
  github = "skycoin"
  #gitlab = "gitlab id"
  twitter = "skycoinproject"
  #linkedin = "linkedin id"
